version: '2'
services:
  webpack:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.dev
    command: yarn start
    volumes:
      - .:/code
    ports:
      - "4000:4000"
volumes:
  webpack:
    driver: local
